// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import ()

type Author struct {
	ID        int32  `json:"id"`
	Bio       string `json:"bio"`
	BirthYear int32  `json:"birth_year"`
}
