// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	GetAuthor(ctx context.Context, id int32) (Author, error)
	GetBioForAuthor(ctx context.Context, id int32) (string, error)
	GetInfoForAuthor(ctx context.Context, id int32) (GetInfoForAuthorRow, error)
	ListAuthors(ctx context.Context) ([]Author, error)
	ListAuthorsByIDs(ctx context.Context, dollar_1 []int32) ([]Author, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error
}

var _ Querier = (*Queries)(nil)
